[pytest]

markers =
    regression: тесты регресса
    smoke: смоук тесты
    integration: интеграционные тесты

addopts =
    -sv
    --clean-alluredir
    --reruns=1
    --only-rerun TimeoutException
    --only-rerun HTTPSConnectionPool
    --only-rerun StaleElementReferenceException
    --only-rerun InvalidSessionIdException
